(function(){var h={},mt={},c={id:"0c0e9d9b1e7d617b3e6842e85b9fb068",dm:["jianshu.com"],js:"tongji.baidu.com/hm-web/js/",etrk:[],cetrk:[],cptrk:[],icon:'',ctrk:true,align:0,nv:-1,vdur:1800000,age:31536000000,rec:0,rp:[],trust:0,vcard:0,qiao:0,lxb:0,kbtrk:1,pt:0,spa:0,aet:'',hca:'0BAC8FECD0FF06F0',conv:0,med:0,cvcc:'',cvcf:[],apps:''};var r=void 0,t=!0,v=null,x=!1;mt.cookie={};mt.cookie.set=function(a,b,e){var d;e.Q&&(d=new Date,d.setTime(d.getTime()+e.Q));document.cookie=a+"="+b+(e.domain?"; domain="+e.domain:"")+(e.path?"; path="+e.path:"")+(d?"; expires="+d.toGMTString():"")+(e.Ec?"; secure":"")};mt.cookie.get=function(a){return(a=RegExp("(^| )"+a+"=([^;]*)(;|$)").exec(document.cookie))?a[2]:v};
mt.cookie.ac=function(a,b){try{var e="Hm_ck_"+ +new Date;mt.cookie.set(e,"is-cookie-enabled",{domain:a,path:b,Q:r});var d="is-cookie-enabled"===mt.cookie.get(e)?"1":"0";mt.cookie.set(e,"",{domain:a,path:b,Q:-1});return d}catch(f){return"0"}};mt.lang={};mt.lang.e=function(a,b){return"[object "+b+"]"==={}.toString.call(a)};mt.lang.ya=function(a){return mt.lang.e(a,"Number")&&isFinite(a)};mt.lang.L=function(a){return mt.lang.e(a,"String")};mt.lang.isArray=function(a){return mt.lang.e(a,"Array")};
mt.lang.g=function(a){return a.replace?a.replace(/'/g,"'0").replace(/\*/g,"'1").replace(/!/g,"'2"):a};mt.lang.trim=function(a){return a.replace(/^\s+|\s+$/g,"")};mt.lang.K=function(a,b){var e=x;if(a==v||!mt.lang.e(a,"Array")||b===r)return e;if(Array.prototype.indexOf)e=-1!==a.indexOf(b);else for(var d=0;d<a.length;d++)if(a[d]===b){e=t;break}return e};mt.url={};mt.url.m=function(a,b){var e=a.match(RegExp("(^|&|\\?|#)("+b+")=([^&#]*)(&|$|#)",""));return e?e[3]:v};
mt.url.Bc=function(a){return(a=a.match(/^(https?:)\/\//))?a[1]:v};mt.url.Gb=function(a){return(a=a.match(/^(https?:\/\/)?([^\/\?#]*)/))?a[2].replace(/.*@/,""):v};mt.url.S=function(a){return(a=mt.url.Gb(a))?a.replace(/:\d+$/,""):a};mt.url.ta=function(a){return(a=a.match(/^(https?:\/\/)?[^\/]*(.*)/))?a[2].replace(/[\?#].*/,"").replace(/^$/,"/"):v};
(function(){var a=mt.lang,b=mt.url;mt.f={};mt.f.Ma=function(e){return document.getElementById(e)};mt.f.Na=function(e){if(!e)return v;try{e=String(e);if(0===e.indexOf("!HMCQ!"))return e;if(0===e.indexOf("!HMCC!"))return document.querySelector(e.substring(6,e.length));for(var d=e.split(">"),f=document.body,a=d.length-1;0<=a;a--)if(-1<d[a].indexOf("#")){var b=d[a].split("#")[1];(f=document.getElementById(b))||(f=document.getElementById(decodeURIComponent(b)));d=d.splice(a+1,d.length-(a+1));break}for(e=
0;f&&e<d.length;){var l=String(d[e]).toLowerCase();if(!("html"===l||"body"===l)){var a=0,q=d[e].match(/\[(\d+)\]/i),b=[];if(q)a=q[1]-1,l=l.split("[")[0];else if(1!==f.childNodes.length){for(var w=0,s=0,n=f.childNodes.length;s<n;s++){var u=f.childNodes[s];1===u.nodeType&&u.nodeName.toLowerCase()===l&&w++;if(1<w)return v}if(1!==w)return v}for(w=0;w<f.childNodes.length;w++)1===f.childNodes[w].nodeType&&f.childNodes[w].nodeName.toLowerCase()===l&&b.push(f.childNodes[w]);if(!b[a])return v;f=b[a]}e++}return f}catch(g){return v}};
mt.f.ta=function(e,d){var a=[],b=[];if(!e)return b;for(;e.parentNode!=v;){for(var k=0,l=0,q=e.parentNode.childNodes.length,w=0;w<q;w++){var s=e.parentNode.childNodes[w];if(s.nodeName===e.nodeName&&(k++,s===e&&(l=k),0<l&&1<k))break}if((q=""!==e.id)&&d){a.unshift("#"+encodeURIComponent(e.id));break}else q&&(q="#"+encodeURIComponent(e.id),q=0<a.length?q+">"+a.join(">"):q,b.push(q)),a.unshift(encodeURIComponent(String(e.nodeName).toLowerCase())+(1<k?"["+l+"]":""));e=e.parentNode}b.push(a.join(">"));return b};
mt.f.Pa=function(a){return(a=mt.f.ta(a,t))&&a.length?String(a[0]):""};mt.f.Lb=function(a){return mt.f.ta(a,x)};mt.f.Bb=function(a){var d;for(d="A";(a=a.parentNode)&&1==a.nodeType;)if(a.tagName==d)return a;return v};mt.f.Db=function(a){return 9===a.nodeType?a:a.ownerDocument||a.document};mt.f.Jb=function(a){var d={top:0,left:0};if(!a)return d;var f=mt.f.Db(a).documentElement;"undefined"!==typeof a.getBoundingClientRect&&(d=a.getBoundingClientRect());return{top:d.top+(window.pageYOffset||f.scrollTop)-
(f.clientTop||0),left:d.left+(window.pageXOffset||f.scrollLeft)-(f.clientLeft||0)}};mt.f.getAttribute=function(a,d){var f=a.getAttribute&&a.getAttribute(d)||v;if(!f&&a.attributes&&a.attributes.length)for(var b=a.attributes,k=b.length,l=0;l<k;l++)b[l].nodeName===d&&(f=b[l].nodeValue);return f};mt.f.aa=function(a){var d="document";a.tagName!==r&&(d=a.tagName);return d.toLowerCase()};mt.f.Ob=function(b){var d="";b.textContent?d=a.trim(b.textContent):b.innerText&&(d=a.trim(b.innerText));d&&(d=d.replace(/\s+/g,
" ").substring(0,255));return d};mt.f.ra=function(e,d){var f;a.L(e)&&0===String(e).indexOf("!HMCQ!")?(f=String(e),f=b.m(document.location.href,f.substring(6,f.length))):a.L(e)||(f=mt.f.aa(e),"input"===f&&d&&("button"===e.type||"submit"===e.type)?f=a.trim(e.value)||"":"input"===f&&!d&&"password"!==e.type?f=a.trim(e.value)||"":"img"===f?(f=mt.f.getAttribute,f=f(e,"alt")||f(e,"title")||f(e,"src")):f="body"===f||"html"===f?["(hm-default-content-for-",f,")"].join(""):mt.f.Ob(e));return String(f||"").substring(0,
255)};(function(){(mt.f.Xa=function(){function a(){if(!a.ca){a.ca=t;for(var d=0,b=m.length;d<b;d++)m[d]()}}function d(){try{document.documentElement.doScroll("left")}catch(b){setTimeout(d,1);return}a()}var b=x,m=[],k;document.addEventListener?k=function(){document.removeEventListener("DOMContentLoaded",k,x);a()}:document.attachEvent&&(k=function(){"complete"===document.readyState&&(document.detachEvent("onreadystatechange",k),a())});(function(){if(!b)if(b=t,"complete"===document.readyState)a.ca=t;
else if(document.addEventListener)document.addEventListener("DOMContentLoaded",k,x),window.addEventListener("load",a,x);else if(document.attachEvent){document.attachEvent("onreadystatechange",k);window.attachEvent("onload",a);var l=x;try{l=window.frameElement==v}catch(q){}document.documentElement.doScroll&&l&&d()}})();return function(d){a.ca?d():m.push(d)}}()).ca=x})();return mt.f})();mt.event={};
mt.event.d=function(a,b,e){a.attachEvent?a.attachEvent("on"+b,function(d){e.call(a,d)}):a.addEventListener&&a.addEventListener(b,e,x)};mt.event.preventDefault=function(a){a.preventDefault?a.preventDefault():a.returnValue=x};
(function(){var a=mt.event;mt.h={};mt.h.xa=/msie (\d+\.\d+)/i.test(navigator.userAgent);mt.h.Hb=function(){if(document.documentMode)return document.documentMode;var a=/msie (\d+\.\d+)/i.exec(navigator.userAgent);return a?+a[1]||0:0};mt.h.cookieEnabled=navigator.cookieEnabled;mt.h.javaEnabled=navigator.javaEnabled();mt.h.language=navigator.language||navigator.browserLanguage||navigator.systemLanguage||navigator.userLanguage||"";mt.h.kc=(window.screen.width||0)+"x"+(window.screen.height||0);mt.h.colorDepth=
window.screen.colorDepth||0;mt.h.T=function(){var a;a=a||document;return parseInt(window.pageYOffset||a.documentElement.scrollTop||a.body&&a.body.scrollTop||0,10)};mt.h.J=function(){var a=document;return parseInt(window.innerHeight||a.documentElement.clientHeight||a.body&&a.body.clientHeight||0,10)};mt.h.orientation=0;(function(){function b(){var a=0;window.orientation!==r&&(a=window.orientation);screen&&(screen.orientation&&screen.orientation.angle!==r)&&(a=screen.orientation.angle);mt.h.orientation=
a}b();a.d(window,"orientationchange",b)})();return mt.h})();mt.o={};mt.o.parse=function(a){return(new Function("return ("+a+")"))()};
mt.o.stringify=function(){function a(a){/["\\\x00-\x1f]/.test(a)&&(a=a.replace(/["\\\x00-\x1f]/g,function(a){var d=e[a];if(d)return d;d=a.charCodeAt();return"\\u00"+Math.floor(d/16).toString(16)+(d%16).toString(16)}));return'"'+a+'"'}function b(a){return 10>a?"0"+a:a}var e={"\b":"\\b","\t":"\\t","\n":"\\n","\f":"\\f","\r":"\\r",'"':'\\"',"\\":"\\\\"};return function(d){switch(typeof d){case "undefined":return"undefined";case "number":return isFinite(d)?String(d):"null";case "string":return a(d);case "boolean":return String(d);
default:if(d===v)return"null";if(d instanceof Array){var f=["["],e=d.length,k,l,q;for(l=0;l<e;l++)switch(q=d[l],typeof q){case "undefined":case "function":case "unknown":break;default:k&&f.push(","),f.push(mt.o.stringify(q)),k=1}f.push("]");return f.join("")}if(d instanceof Date)return'"'+d.getFullYear()+"-"+b(d.getMonth()+1)+"-"+b(d.getDate())+"T"+b(d.getHours())+":"+b(d.getMinutes())+":"+b(d.getSeconds())+'"';k=["{"];l=mt.o.stringify;for(e in d)if(Object.prototype.hasOwnProperty.call(d,e))switch(q=
d[e],typeof q){case "undefined":case "unknown":case "function":break;default:f&&k.push(","),f=1,k.push(l(e)+":"+l(q))}k.push("}");return k.join("")}}}();mt.localStorage={};mt.localStorage.ka=function(){if(!mt.localStorage.l)try{mt.localStorage.l=document.createElement("input"),mt.localStorage.l.type="hidden",mt.localStorage.l.style.display="none",mt.localStorage.l.addBehavior("#default#userData"),document.getElementsByTagName("head")[0].appendChild(mt.localStorage.l)}catch(a){return x}return t};
mt.localStorage.set=function(a,b,e){var d=new Date;d.setTime(d.getTime()+e||31536E6);try{window.localStorage?(b=d.getTime()+"|"+b,window.localStorage.setItem(a,b)):mt.localStorage.ka()&&(mt.localStorage.l.expires=d.toUTCString(),mt.localStorage.l.load(document.location.hostname),mt.localStorage.l.setAttribute(a,b),mt.localStorage.l.save(document.location.hostname))}catch(f){}};
mt.localStorage.get=function(a){if(window.localStorage){if(a=window.localStorage.getItem(a)){var b=a.indexOf("|"),e=a.substring(0,b)-0;if(e&&e>(new Date).getTime())return a.substring(b+1)}}else if(mt.localStorage.ka())try{return mt.localStorage.l.load(document.location.hostname),mt.localStorage.l.getAttribute(a)}catch(d){}return v};
mt.localStorage.remove=function(a){if(window.localStorage)window.localStorage.removeItem(a);else if(mt.localStorage.ka())try{mt.localStorage.l.load(document.location.hostname),mt.localStorage.l.removeAttribute(a),mt.localStorage.l.save(document.location.hostname)}catch(b){}};mt.sessionStorage={};mt.sessionStorage.set=function(a,b){try{window.sessionStorage&&window.sessionStorage.setItem(a,b)}catch(e){}};
mt.sessionStorage.get=function(a){try{return window.sessionStorage?window.sessionStorage.getItem(a):v}catch(b){return v}};mt.sessionStorage.remove=function(a){try{window.sessionStorage&&window.sessionStorage.removeItem(a)}catch(b){}};mt.ab={};mt.ab.log=function(a,b){var e=new Image,d="mini_tangram_log_"+Math.floor(2147483648*Math.random()).toString(36);window[d]=e;e.onload=function(){e.onload=v;e=window[d]=v;b&&b(a)};e.src=a};mt.Da={};
mt.Da.Pb=function(){var a="";if(navigator.plugins&&navigator.mimeTypes.length){var b=navigator.plugins["Shockwave Flash"];b&&b.description&&(a=b.description.replace(/^.*\s+(\S+)\s+\S+$/,"$1"))}else if(window.ActiveXObject)try{if(b=new ActiveXObject("ShockwaveFlash.ShockwaveFlash"))(a=b.GetVariable("$version"))&&(a=a.replace(/^.*\s+(\d+),(\d+).*$/,"$1.$2"))}catch(e){}return a};
mt.Da.Ac=function(a,b,e,d,f){return'<object classid="clsid:d27cdb6e-ae6d-11cf-96b8-444553540000" id="'+a+'" width="'+e+'" height="'+d+'"><param name="movie" value="'+b+'" /><param name="flashvars" value="'+(f||"")+'" /><param name="allowscriptaccess" value="always" /><embed type="application/x-shockwave-flash" name="'+a+'" width="'+e+'" height="'+d+'" src="'+b+'" flashvars="'+(f||"")+'" allowscriptaccess="always" /></object>'};
(function(){function a(){for(var a=x,e=document.getElementsByTagName("script"),d=e.length,d=100<d?100:d,f=0;f<d;f++){var m=e[f].src;if(m&&0===m.indexOf("https://hm.baidu.com/h")){a=t;break}}return a}return h.Ab=a})();var A=h.Ab;
h.z={Cc:"http://tongji.baidu.com/hm-web/welcome/ico",Ca:"hm.baidu.com/hm.gif",lb:/^(tongji|hmcdn).baidu.com$/,cb:"tongji.baidu.com",Ub:"hmmd",Vb:"hmpl",wc:"utm_medium",Tb:"hmkw",yc:"utm_term",Rb:"hmci",vc:"utm_content",Wb:"hmsr",xc:"utm_source",Sb:"hmcu",uc:"utm_campaign",M:0,H:Math.round(+new Date/1E3),protocol:"https:"===document.location.protocol?"https:":"http:",ea:A()||"https:"===document.location.protocol?"https:":"http:",Dc:0,tb:6E5,bc:6E5,lc:5E3,ub:5,O:1024,rb:1,X:2147483647,bb:"hca kb cc cf ci ck cl cm cp cu cw ds vl ep et fl ja ln lo lt rnd si su v cv lv api sn p ct u tt".split(" "),
U:t,Ja:["a","input","button"],nb:{id:"data-hm-id",na:"data-hm-class",Ga:"data-hm-xpath",content:"data-hm-content",Ea:"data-hm-tag",link:"data-hm-link"},Ia:"data-hm-enabled",Ha:"data-hm-disabled",gc:"https://hmcdn.baidu.com/static/tongji/plugins/",Wa:["UrlChangeTracker"]};(function(){var a={D:{},d:function(a,e){this.D[a]=this.D[a]||[];this.D[a].push(e)},I:function(a,e){this.D[a]=this.D[a]||[];for(var d=this.D[a].length,f=0;f<d;f++)this.D[a][f](e)}};return h.w=a})();
(function(){function a(a,d){var f=document.createElement("script");f.charset="utf-8";b.e(d,"Function")&&(f.readyState?f.onreadystatechange=function(){if("loaded"===f.readyState||"complete"===f.readyState)f.onreadystatechange=v,d()}:f.onload=function(){d()});f.src=a;var m=document.getElementsByTagName("script")[0];m.parentNode.insertBefore(f,m)}var b=mt.lang;return h.load=a})();
(function(){var a=mt.cookie,b=mt.localStorage,e=mt.sessionStorage,d={getData:function(d){try{return a.get(d)||e.get(d)||b.get(d)}catch(m){}},setData:function(f,m,k){try{a.set(f,m,{domain:d.R(),path:d.$(),Q:k}),k?b.set(f,m,k):e.set(f,m)}catch(l){}},jc:function(f){try{a.set(f,"",{domain:d.R(),path:d.$(),Q:-1}),e.remove(f),b.remove(f)}catch(m){}},V:function(a,d){a="."+a.replace(/:\d+/,"");d="."+d.replace(/:\d+/,"");var b=a.indexOf(d);return-1<b&&b+d.length===a.length},da:function(a,d){a=a.replace(/^https?:\/\//,
"");return 0===a.indexOf(d)},R:function(){for(var a=document.location.hostname,b=0,e=c.dm.length;b<e;b++)if(d.V(a,c.dm[b]))return c.dm[b].replace(/(:\d+)?[/?#].*/,"");return a},$:function(){for(var a=0,b=c.dm.length;a<b;a++){var e=c.dm[a];if(-1<e.indexOf("/")&&d.da(document.location.href,e))return e.replace(/^[^/]+(\/.*)/,"$1")+"/"}return"/"}};return h.oa=d})();
(function(){var a=mt.lang,b=mt.o,e=h.oa,d={pageview:{},session:{},autoEventTracking:{},customEvent:{},user:{}},f={user:1,session:2,pageview:3,autoEventTracking:3,customEvent:3,others:3},m=["session","user"],k="Hm_up_"+c.id,l={init:function(){l.Zb()},Zb:function(){try{var f=b.parse(decodeURIComponent(e.getData(k)));a.e(f,"Object")&&(d.user=f)}catch(l){}},A:function(a){var b={};d[a]!==r&&(b=d[a]);a=this.ua();for(var f in b)b.hasOwnProperty(f)&&(a[f]=b[f]);return a},ua:function(){for(var a={},b,f=m.length-
1;0<=f;f--){b=d[m[f]];for(var e in b)b.hasOwnProperty(e)&&(a[e]=b[e])}return a},setProperty:function(f,e,k){var n=d[f];if(a.e(n,"Object")&&a.e(e,"Object")){for(var m in e)if(e.hasOwnProperty(m)){var g=a.g(String(m));if(k||!((/^_/.test(g)||/_$/.test(g))&&"_iden"!==g)){var p=e[m];if(p==v)delete n[g];else{if(a.e(p,"Object")||a.e(p,"Array"))p=b.stringify(p);p=a.g(String(p));l.$b(f,g,p)&&(n[g]={value:p,scope:l.Qa(f)})}}}"user"===f&&l.Aa()}},r:function(b){b!==r&&("userId"===b&&a.e(d.user,"Object")?(delete d.user.uid_,
l.Aa()):"user"===b&&a.e(d.user,"Object")?(b=d.user.uid_,d.user=b===r?{}:{uid_:b},l.Aa()):d[b]!==r&&(d[b]={}))},Aa:function(){try{e.setData(k,encodeURIComponent(b.stringify(d.user)),c.age)}catch(a){}},$b:function(a,b,f){var e=t,k=d[a];if(256<encodeURIComponent(String(b)).length||256<encodeURIComponent(String(f)).length)e=x;else{var g=k[b];k[b]={value:f,scope:l.Qa(a)};a=l.N(l.A(a));2048<encodeURIComponent(a).length&&(g!==r?k[b]=g:delete k[b],e=x)}return e},N:function(a){var d=[],b,f;for(f in a)a.hasOwnProperty(f)&&
(b=[f,a[f].value],(1===a[f].scope||2===a[f].scope)&&b.push(a[f].scope),d.push(b.join("*")));return d.join("!")},Qa:function(a){a=f[a];return a!==r?a:f.others}};return h.P=l})();
(function(){var a=mt.f,b=mt.lang,e=mt.o,d=h.w,f=h.P,m=f.N;if(b.isArray(c.cptrk)&&0<c.cptrk.length){var k={Va:{},ha:{},init:function(){for(var a,d=0;d<c.cptrk.length;d++)try{if(a=e.parse(decodeURIComponent(String(c.cptrk[d]))),a.a!==r&&b.e(a.a,"Object")){var f=a.a,m;for(m in f)f.hasOwnProperty(m)&&(k.ha[m]=String(f[m]))}}catch(n){}},Ua:function(){var d,b,f;for(f in k.ha)if(k.ha.hasOwnProperty(f)&&k.Va[f]===r&&(d=k.ha[f],d=a.Na(d)))b=b===r?{}:b,b[f]=a.ra(d,x),k.Va[f]=t;return b},va:function(){var a=
k.Ua();a&&k.oc(a)},Yb:function(){"MutationObserver"in window?(new MutationObserver(k.va)).observe(document.body,{childList:t,subtree:t}):window.setInterval(k.va,15E3)},oc:function(a){if(b.e(a,"Object")){f.setProperty("pageview",a);a=h.c.b.p;var d=h.c.b.ep;h.c.b.et=9;h.c.b.ep="";h.c.b.p=m(f.A("pageview"));h.c.i();h.c.b.p=a;h.c.b.ep=d;f.r("pageview")}}};k.init();d.d("pv-b",function(){var a=k.Ua();a&&f.setProperty("pageview",a)});k.Yb();a.Xa(k.va)}})();
(function(){var a=mt.lang,b=mt.f,e={Z:function(a,f){return function(m){var k=m.target||m.srcElement;if(k){var l=k.getAttribute(a.ia);m=m.clientX+":"+m.clientY;if(l&&l===m)k.removeAttribute(a.ia);else if(f&&0<f.length&&(k=b.Lb(k))&&k.length)if(l=k.length,m=k[k.length-1],1E4>l*m.split(">").length)for(m=0;m<l;m++)e.$a(a,k[m]);else e.$a(a,m)}}},$a:function(d,b){for(var e={},k=String(b).split(">").length,l=0;l<k;l++)e[b]="",b=b.substring(0,b.lastIndexOf(">"));d&&(a.e(d,"Object")&&d.Ka)&&d.Ka(e)},ic:function(a,
b){return function(e){(e.target||e.srcElement).setAttribute(a.ia,e.clientX+":"+e.clientY);a&&a.s&&(b?a.s(b):a.s("#"+encodeURIComponent(this.id),e.type))}}};return h.qa=e})();
(function(){var a=mt.f,b=mt.o,e=mt.event,d=mt.lang,f=h.qa,m=h.P,k=m.N,l={ia:"HM_ce",fb:function(){if(c.cetrk&&c.cetrk.length){e.d(document,"click",f.Z(l,c.cetrk));for(var d=0,k=c.cetrk.length;d<k;d++){var m;try{m=b.parse(decodeURIComponent(String(c.cetrk[d])))}catch(n){m={}}var u=m.p||"";-1===u.indexOf(">")&&(0===u.indexOf("#")&&(u=u.substring(1)),(u=a.Ma(u))&&e.d(u,"click",f.ic(l,m)))}}},Ka:function(a){if(c.cetrk&&c.cetrk.length)for(var d=0,f=c.cetrk.length;d<f;d++){var e;try{e=b.parse(decodeURIComponent(String(c.cetrk[d])))}catch(k){e=
{}}var g=l.Eb(e.p,a);g&&l.s(e,g)}},Eb:function(a,d){a=String(a);if(0<a.indexOf("*")){var b=RegExp("^"+a.replace(/\[/g,"\\[").replace(/\]/g,"\\]").replace(/\*/,"\\d+")+"$"),f;for(f in d)if(d.hasOwnProperty(f)&&b.test(f))return f;return v}return d.hasOwnProperty(a)?a:v},s:function(b,f){h.c.b.et=7;var e=b&&b.k||"",e=d.g(e),n={};if(b&&b.a&&d.e(b.a,"Object")){var u=b.a,g;for(g in u)if(u.hasOwnProperty(g)){var p=l.Mb(u[g]||"",f),p=p?a.ra(p,x):"";n[g]=p}}n._iden=e;m.setProperty("customEvent",n);h.c.b.ep=
"";h.c.b.p=k(m.A("customEvent"));h.c.i();h.c.b.p="";m.r("customEvent")},Mb:function(d,b){d=String(d);b=String(b);if(0<d.indexOf("*")){var f=/.*\[(\d+)\]$/.exec(b);d=d.replace("*",f?f[1]:"1")}return a.Na(d)}};h.w.d("pv-b",l.fb);return l})();
(function(){var a=mt.f,b=mt.lang,e=mt.event,d=mt.h,f=h.z,m=h.w,k=[],l={eb:function(){c.ctrk&&(e.d(document,"mouseup",l.qb()),e.d(window,"unload",function(){l.fa()}),setInterval(function(){l.fa()},f.tb))},qb:function(){return function(a){a=l.Cb(a);if(""!==a){var d=(f.ea+"//"+f.Ca+"?"+h.c.Za().replace(/ep=[^&]*/,"ep="+encodeURIComponent(a))).length;d+(f.X+"").length>f.O||(d+encodeURIComponent(k.join("!")+(k.length?"!":"")).length+(f.X+"").length>f.O&&l.fa(),k.push(a),(k.length>=f.ub||/\*a\*/.test(a))&&
l.fa())}}},Cb:function(e){var k=e.target||e.srcElement;if(0===f.rb){var n=(k.tagName||"").toLowerCase();if("embed"==n||"object"==n)return""}var m;d.xa?(m=Math.max(document.documentElement.scrollTop,document.body.scrollTop),n=Math.max(document.documentElement.scrollLeft,document.body.scrollLeft),n=e.clientX+n,m=e.clientY+m):(n=e.pageX,m=e.pageY);e=l.Ib(e,k,n,m);var g=window.innerWidth||document.documentElement.clientWidth||document.body.offsetWidth;switch(c.align){case 1:n-=g/2;break;case 2:n-=g}g=
[];g.push(n);g.push(m);g.push(e.dc);g.push(e.ec);g.push(e.hc);g.push(b.g(e.fc));g.push(e.zc);g.push(e.Qb);(k="a"===(k.tagName||"").toLowerCase()?k:a.Bb(k))?(g.push("a"),g.push(b.g(encodeURIComponent(k.href)))):g.push("b");return g.join("*")},Ib:function(e,f,k,l){e=a.Pa(f);var g=0,p=0,y=0,z=0;if(f&&(g=f.offsetWidth||f.clientWidth,p=f.offsetHeight||f.clientHeight,z=a.Jb(f),y=z.left,z=z.top,b.e(f.getBBox,"Function")&&(p=f.getBBox(),g=p.width,p=p.height),"html"===(f.tagName||"").toLowerCase()))g=Math.max(g,
f.clientWidth),p=Math.max(p,f.clientHeight);return{dc:Math.round(100*((k-y)/g)),ec:Math.round(100*((l-z)/p)),hc:d.orientation,fc:e,zc:g,Qb:p}},fa:function(){0!==k.length&&(h.c.b.et=2,h.c.b.ep=k.join("!"),h.c.i(),k=[])}},q={ib:function(){c.ctrk&&setInterval(q.mc,f.lc)},mc:function(){var a=d.T()+d.J();0<a-h.c.b.vl&&(h.c.b.vl=a)}};m.d("pv-b",l.eb);m.d("pv-b",q.ib);return l})();
(function(){var a=mt.lang,b=mt.f,e=mt.event,d=mt.h,f=h.z,m=h.w,k=h.P,l=k.N,q=+new Date,w=[],s={Z:function(){return function(d){if(h.c&&h.c.U&&c.aet&&c.aet.length){var e=d.target||d.srcElement;if(e){var g=h.c.Ja,p=b.getAttribute(e,f.Ia)!=v?t:x;if(b.getAttribute(e,f.Ha)==v)if(p)s.la(s.sa(e,d));else{var y=b.aa(e);if(a.K(g,"*")||a.K(g,y))s.la(s.sa(e,d));else for(;e.parentNode!=v;){var p=e.parentNode,y=b.aa(p),z="a"===y&&a.K(g,"a")?t:x,y="button"===y&&a.K(g,"button")?t:x,B=b.getAttribute(p,f.Ia)!=v?t:
x;if(b.getAttribute(p,f.Ha)==v&&(z||y||B)){s.la(s.sa(p,d));break}e=e.parentNode}}}}}},sa:function(e,k){var g={},p=f.nb;g.id=b.getAttribute(e,p.id)||b.getAttribute(e,"id")||"";g.na=b.getAttribute(e,p.na)||b.getAttribute(e,"class")||"";g.Ga=b.getAttribute(e,p.Ga)||b.Pa(e);g.content=b.getAttribute(e,p.content)||b.ra(e,t);g.Ea=b.getAttribute(e,p.Ea)||b.aa(e);g.link=b.getAttribute(e,p.link)||b.getAttribute(e,"href")||"";g.type=k.type||"click";p=a.ya(e.offsetTop)?e.offsetTop:0;"click"===k.type?p=d.xa?k.clientY+
Math.max(document.documentElement.scrollTop,document.body.scrollTop):k.pageY:"touchend"===k.type&&(k.za&&a.e(k.za.changedTouches,"Array")&&k.za.changedTouches.length)&&(p=k.za.changedTouches[0].pageY);g.tc=p;return g},la:function(d){var b=a.g;d=[+new Date-(h.c.F!==r?h.c.F:q),b(d.id),b(d.na),b(d.Ea),b(d.Ga),b(d.link),b(d.content),d.type,d.tc].join("*");s.ma(d);a.e(this.Y(),"Function")&&this.Y()()},ma:function(a){a.length>f.O||(encodeURIComponent(w.join("!")+a).length>f.O&&(s.s(w.join("!")),w=[]),w.push(a))},
s:function(a){h.c.b.et=5;h.c.b.ep=a;h.c.b.p=l(k.A("autoEventTracking"));h.c.i();h.c.b.p=""},Y:function(){return function(){w&&w.length&&(s.s(w.join("!")),w=[])}}};a.L(c.aet)&&""!==c.aet&&m.d("pv-b",function(){e.d(document,"click",s.Z());"ontouchend"in document&&e.d(window,"touchend",s.Z());e.d(window,"unload",s.Y())});return s})();
(function(){var a=mt.event,b=mt.h,e=h.z,d=h.w,f=+new Date,m=[],k=v,l={xb:function(){return function(){h.c&&(h.c.U&&c.aet&&c.aet.length)&&(window.clearTimeout(k),k=window.setTimeout(function(){l.hb(b.T()+b.J())},150))}},hb:function(a){l.ma([+new Date-(h.c.F!==r?h.c.F:f),a].join("*"))},ma:function(a){if(encodeURIComponent(m.join("!")+a).length>e.O||3<m.length)l.s(m.join("!")),m=[];m.push(a)},s:function(a){h.c.b.et=6;h.c.b.vh=b.J();h.c.b.ep=a;h.c.i()},Y:function(){return function(){m&&m.length&&(l.s(m.join("!")),
m=[])}}};mt.lang.L(c.aet)&&""!==c.aet&&d.d("pv-b",function(){a.d(window,"scroll",l.xb());a.d(window,"unload",l.Y())});return l})();
(function(){function a(){return function(){h.c.b.nv=0;h.c.b.st=4;h.c.b.et=3;h.c.b.ep=h.pa.Kb()+","+h.pa.Fb();h.c.i()}}function b(){clearTimeout(z);var a;p&&(a="visible"==document[p]);y&&(a=!document[y]);l="undefined"==typeof a?t:a;if((!k||!q)&&l&&w)g=t,n=+new Date;else if(k&&q&&(!l||!w))g=x,u+=+new Date-n;k=l;q=w;z=setTimeout(b,100)}function e(a){var p=document,d="";if(a in p)d=a;else for(var b=["webkit","ms","moz","o"],e=0;e<b.length;e++){var f=b[e]+a.charAt(0).toUpperCase()+a.slice(1);if(f in p){d=
f;break}}return d}function d(a){if(!("focus"==a.type||"blur"==a.type)||!(a.target&&a.target!=window))w="focus"==a.type||"focusin"==a.type?t:x,b()}var f=mt.event,m=h.w,k=t,l=t,q=t,w=t,s=+new Date,n=s,u=0,g=t,p=e("visibilityState"),y=e("hidden"),z;b();(function(){var a=p.replace(/[vV]isibilityState/,"visibilitychange");f.d(document,a,b);f.d(window,"pageshow",b);f.d(window,"pagehide",b);"object"==typeof document.onfocusin?(f.d(document,"focusin",d),f.d(document,"focusout",d)):(f.d(window,"focus",d),
f.d(window,"blur",d))})();h.pa={Kb:function(){return+new Date-s},Fb:function(){return g?+new Date-n+u:u}};m.d("pv-b",function(){f.d(window,"unload",a())});m.d("duration-send",a());m.d("duration-done",function(){n=s=+new Date;u=0});return h.pa})();
(function(){var a=mt.lang,b=h.z,e=h.load,d={Xb:function(d){if((window._dxt===r||a.e(window._dxt,"Array"))&&"undefined"!==typeof h.c){var m=h.c.R();e([b.protocol,"//datax.baidu.com/x.js?si=",c.id,"&dm=",encodeURIComponent(m)].join(""),d)}},sc:function(d){if(a.e(d,"String")||a.e(d,"Number"))window._dxt=window._dxt||[],window._dxt.push(["_setUserId",d])}};return h.vb=d})();
(function(){function a(a,d,b,e){if(!(a===r||d===r||e===r)){if(""===a)return[d,b,e].join("*");a=String(a).split("!");for(var f,g=x,k=0;k<a.length;k++)if(f=a[k].split("*"),String(d)===f[0]){f[1]=b;f[2]=e;a[k]=f.join("*");g=t;break}g||a.push([d,b,e].join("*"));return a.join("!")}}function b(a){for(var e in a)if({}.hasOwnProperty.call(a,e)){var f=a[e];d.e(f,"Object")||d.e(f,"Array")?b(f):a[e]=String(f)}}var e=mt.url,d=mt.lang,f=mt.o,m=mt.h,k=h.z,l=h.w,q=h.vb,w=h.load,s=h.oa,n=h.P,u=n.N,g={W:[],ga:0,Ta:x,
C:{Fa:"",page:""},init:function(){g.j=0;n.init();l.d("pv-b",function(){g.wb();g.yb()});l.d("pv-d",function(){g.zb();g.C.page=""});l.d("stag-b",function(){h.c.b.api=g.j||g.ga?g.j+"_"+g.ga:"";h.c.b.ct=[decodeURIComponent(s.getData("Hm_ct_"+c.id)||""),g.C.Fa,g.C.page].join("!")});l.d("stag-d",function(){h.c.b.api=0;g.j=0;g.ga=0})},wb:function(){var a=window._hmt||[];if(!a||d.e(a,"Array"))window._hmt={id:c.id,cmd:{},push:function(){for(var a=window._hmt,p=0;p<arguments.length;p++){var b=arguments[p];
d.e(b,"Array")&&(a.cmd[a.id].push(b),"_setAccount"===b[0]&&(1<b.length&&/^[0-9a-f]{32}$/.test(b[1]))&&(b=b[1],a.id=b,a.cmd[b]=a.cmd[b]||[]))}}},window._hmt.cmd[c.id]=[],window._hmt.push.apply(window._hmt,a)},yb:function(){var a=window._hmt;if(a&&a.cmd&&a.cmd[c.id])for(var d=a.cmd[c.id],b=/^_track(Event|MobConv|Order|RTEvent)$/,e=0,f=d.length;e<f;e++){var k=d[e];b.test(k[0])?g.W.push(k):g.Ba(k)}a.cmd[c.id]={push:g.Ba}},zb:function(){if(0<g.W.length)for(var a=0,d=g.W.length;a<d;a++)g.Ba(g.W[a]);g.W=
v},Ba:function(a){var b=a[0];if(g.hasOwnProperty(b)&&d.e(g[b],"Function"))g[b](a)},_setAccount:function(a){1<a.length&&/^[0-9a-f]{32}$/.test(a[1])&&(g.j|=1)},_setAutoPageview:function(a){if(1<a.length&&(a=a[1],x===a||t===a))g.j|=2,h.c.Ra=a},_trackPageview:function(a){if(1<a.length&&a[1].charAt&&"/"===a[1].charAt(0)){g.j|=4;h.c.b.sn=h.c.Oa();h.c.b.et=0;h.c.b.ep="";h.c.b.vl=m.T()+m.J();h.c.b.kb=0;h.c.wa?(h.c.b.nv=0,h.c.b.st=4):h.c.wa=t;var d=h.c.b.u,b=h.c.b.su;h.c.b.u=k.protocol+"//"+document.location.host+
a[1];g.Ta||(h.c.b.su=document.location.href);h.c.b.p=u(n.A("pageview"));h.c.i();h.c.b.u=d;h.c.b.su=b;h.c.b.p="";h.c.F=+new Date;n.r("pageview")}},_trackEvent:function(a){2<a.length&&(g.j|=8,h.c.b.nv=0,h.c.b.st=4,h.c.b.et=4,h.c.b.ep=d.g(a[1])+"*"+d.g(a[2])+(a[3]?"*"+d.g(a[3]):"")+(a[4]?"*"+d.g(a[4]):""),h.c.b.p=u(n.ua()),h.c.i(),h.c.b.p="")},_setCustomVar:function(a){if(!(4>a.length)){var b=a[1],e=a[4]||3;if(0<b&&6>b&&0<e&&4>e){g.ga++;for(var f=(h.c.b.cv||"*").split("!"),k=f.length;k<b-1;k++)f.push("*");
f[b-1]=e+"*"+d.g(a[2])+"*"+d.g(a[3]);h.c.b.cv=f.join("!");a=h.c.b.cv.replace(/[^1](\*[^!]*){2}/g,"*").replace(/((^|!)\*)+$/g,"");""!==a?s.setData("Hm_cv_"+c.id,encodeURIComponent(a),c.age):s.jc("Hm_cv_"+c.id)}}},_setUserTag:function(b){if(!(3>b.length)){var e=d.g(b[1]);b=d.g(b[2]);if(e!==r&&b!==r){var f=decodeURIComponent(s.getData("Hm_ct_"+c.id)||""),f=a(f,e,1,b);s.setData("Hm_ct_"+c.id,encodeURIComponent(f),c.age)}}},_setVisitTag:function(b){if(!(3>b.length)){var e=d.g(b[1]);b=d.g(b[2]);if(e!==
r&&b!==r){var f=g.C.Fa,f=a(f,e,2,b);g.C.Fa=f}}},_setPageTag:function(b){if(!(3>b.length)){var e=d.g(b[1]);b=d.g(b[2]);if(e!==r&&b!==r){var f=g.C.page,f=a(f,e,3,b);g.C.page=f}}},_setReferrerOverride:function(a){1<a.length&&(h.c.b.su=a[1].charAt&&"/"===a[1].charAt(0)?k.protocol+"//"+window.location.host+a[1]:a[1],g.Ta=t)},_trackOrder:function(a){a=a[1];d.e(a,"Object")&&(b(a),g.j|=16,h.c.b.nv=0,h.c.b.st=4,h.c.b.et=94,h.c.b.ep=f.stringify(a),h.c.b.p=u(n.ua()),h.c.i(),h.c.b.p="")},_trackMobConv:function(a){if(a=
{webim:1,tel:2,map:3,sms:4,callback:5,share:6}[a[1]])g.j|=32,h.c.b.et=93,h.c.b.ep=a,h.c.i()},_setDataxId:function(a){a=a[1];q.Xb();q.sc(a)},_setUserId:function(a){a=a[1];if(a!==r&&(d.L(a)||d.ya(a))){var b=n.A("user").uid_;if(!(b&&b.value===d.g(String(a)))){var b=h.c.b.p,e=h.c.b.ep;h.c.b.et=8;h.c.b.ep="";h.c.b.p="uid_*"+d.g(String(a));h.c.i();var f={};f.uid_=a;n.setProperty("user",f,t);h.c.b.p=b;h.c.b.ep=e}}},_clearUserId:function(a){1<a.length&&t===a[1]&&n.r("userId")},_setUserProperty:function(a){a=
a[1];d.e(a,"Object")&&n.setProperty("user",a)},_clearUserProperty:function(a){1<a.length&&t===a[1]&&n.r("user")},_setSessionProperty:function(a){a=a[1];d.e(a,"Object")&&n.setProperty("session",a)},_clearSessionProperty:function(a){1<a.length&&t===a[1]&&n.r("session")},_setPageviewProperty:function(a){a=a[1];d.e(a,"Object")&&n.setProperty("pageview",a)},_clearPageviewProperty:function(a){1<a.length&&t===a[1]&&n.r("pageview")},_setAutoEventTrackingProperty:function(a){a=a[1];d.e(a,"Object")&&n.setProperty("autoEventTracking",
a)},_clearAutoEventTrackingProperty:function(a){1<a.length&&t===a[1]&&n.r("autoEventTracking")},_setAutoTracking:function(a){if(1<a.length&&(a=a[1],x===a||t===a))h.c.Sa=a},_setAutoEventTracking:function(a){if(1<a.length&&(a=a[1],x===a||t===a))h.c.U=a},_trackPageDuration:function(a){1<a.length?(a=a[1],2===String(a).split(",").length&&(h.c.b.et=3,h.c.b.ep=a,h.c.i())):l.I("duration-send");l.I("duration-done")},_require:function(a){1<a.length&&(a=a[1],k.lb.test(e.S(a))&&w(a))},_providePlugin:function(a){if(1<
a.length){var b=window._hmt,e=a[1];a=a[2];if(d.K(k.Wa,e)&&d.e(a,"Function")&&(b.plugins=b.plugins||{},b.G=b.G||{},b.plugins[e]=a,b.B=b.B||[],a=b.B.slice(),e&&a.length&&a[0][1]===e))for(var f=0,g=a.length;f<g;f++){var l=a[f][2]||{};if(b.plugins[e]&&!b.G[e])b.G[e]=new b.plugins[e](l),b.B.shift();else break}}},_requirePlugin:function(a){if(1<a.length){var b=window._hmt,e=a[1],f=a[2]||{};if(d.K(k.Wa,e))if(b.plugins=b.plugins||{},b.G=b.G||{},b.plugins[e]&&!b.G[e])b.G[e]=new b.plugins[e](f);else{b.B=b.B||
[];for(var f=0,l=b.B.length;f<l;f++)if(b.B[f][1]===e)return;b.B.push(a);g._require([v,k.gc+e+".js"])}}},_trackCustomEvent:function(a){if(1<a.length){var b=a[1];a=a[2];d.e(a,"Object")||(a={});a._iden=b;n.setProperty("customEvent",a);h.c.b.et=7;h.c.b.ep="";h.c.b.p=u(n.A("customEvent"));h.c.i();h.c.b.p="";n.r("customEvent")}}};g.init();h.mb=g;return h.mb})();
(function(){var a=h.w;c.spa!==r&&"1"===String(c.spa)&&(window._hmt=window._hmt||[],window._hmt.push(["_requirePlugin","UrlChangeTracker"]),a.d("pv-b",function(){""!==window.location.hash&&(h.c.b.u=window.location.href)}))})();
(function(){function a(){"undefined"===typeof window["_bdhm_loaded_"+c.id]&&(window["_bdhm_loaded_"+c.id]=t,this.b={},this.Sa=this.Ra=t,this.U=g.U,this.Ja=f.L(c.aet)&&0<c.aet.length?c.aet.split(","):"",this.wa=x,this.init())}var b=mt.url,e=mt.ab,d=mt.Da,f=mt.lang,m=mt.cookie,k=mt.h,l=mt.sessionStorage,q=mt.o,w=mt.event,s=h.oa,n=h.P,u=n.N,g=h.z,p=h.load,y=h.w;a.prototype={V:function(a,b){a="."+a.replace(/:\d+/,"");b="."+b.replace(/:\d+/,"");var d=a.indexOf(b);return-1<d&&d+b.length===a.length},da:function(a,
b){a=a.replace(/^https?:\/\//,"");return 0===a.indexOf(b)},ba:function(a){for(var d=0;d<c.dm.length;d++)if(-1<c.dm[d].indexOf("/")){if(this.da(a,c.dm[d]))return t}else{var e=b.S(a);if(e&&this.V(e,c.dm[d]))return t}return x},R:function(){for(var a=document.location.hostname,b=0,d=c.dm.length;b<d;b++)if(this.V(a,c.dm[b]))return c.dm[b].replace(/(:\d+)?[/?#].*/,"");return a},$:function(){for(var a=0,b=c.dm.length;a<b;a++){var d=c.dm[a];if(-1<d.indexOf("/")&&this.da(document.location.href,d))return d.replace(/^[^/]+(\/.*)/,
"$1")+"/"}return"/"},Nb:function(){if(!document.referrer)return g.H-g.M>c.vdur?1:4;var a=x;this.ba(document.referrer)&&this.ba(document.location.href)?a=t:(a=b.S(document.referrer),a=this.V(a||"",document.location.hostname));return a?g.H-g.M>c.vdur?1:4:3},qc:function(){var a,b,d,e,f;g.M=s.getData("Hm_lpvt_"+c.id)||0;13===g.M.length&&(g.M=Math.round(g.M/1E3));b=this.Nb();a=4!==b?1:0;if(d=s.getData("Hm_lvt_"+c.id)){e=d.split(",");for(f=e.length-1;0<=f;f--)13===e[f].length&&(e[f]=""+Math.round(e[f]/
1E3));for(;2592E3<g.H-e[0];)e.shift();f=4>e.length?2:3;for(1===a&&e.push(g.H);4<e.length;)e.shift();d=e.join(",");e=e[e.length-1]}else d=g.H,e="",f=1;s.setData("Hm_lvt_"+c.id,d,c.age);s.setData("Hm_lpvt_"+c.id,g.H);d=m.ac(this.R(),this.$());if(0===c.nv&&this.ba(document.location.href)&&(""===document.referrer||this.ba(document.referrer)))a=0,b=4;this.b.nv=a;this.b.st=b;this.b.cc=d;this.b.lt=e;this.b.lv=f},Za:function(){for(var a=[],b=this.b.et,d=+new Date,e=0,f=g.bb.length;e<f;e++){var k=g.bb[e],
l=this.b[k];"undefined"!==typeof l&&""!==l&&("tt"!==k||"tt"===k&&0===b)&&(("ct"!==k||"ct"===k&&0===b)&&("kb"!==k||"kb"===k&&3===b))&&a.push(k+"="+encodeURIComponent(l))}switch(b){case 0:this.b.rt&&a.push("rt="+encodeURIComponent(this.b.rt));break;case 5:a.push("_lpt="+this.F);a.push("_ct="+d);break;case 6:a.push("_lpt="+this.F);a.push("_ct="+d);break;case 90:this.b.rt&&a.push("rt="+this.b.rt)}return a.join("&")},rc:function(){this.qc();this.b.si=c.id;this.b.sn=this.Oa();this.b.su=document.referrer;
this.b.ds=k.kc;this.b.cl=k.colorDepth+"-bit";this.b.ln=String(k.language).toLowerCase();this.b.ja=k.javaEnabled?1:0;this.b.ck=k.cookieEnabled?1:0;this.b.lo="number"===typeof _bdhm_top?1:0;this.b.fl=d.Pb();this.b.v="1.2.65";this.b.cv=decodeURIComponent(s.getData("Hm_cv_"+c.id)||"");this.b.tt=document.title||"";this.b.vl=k.T()+k.J();var a=document.location.href;this.b.cm=b.m(a,g.Ub)||"";this.b.cp=b.m(a,g.Vb)||b.m(a,g.wc)||"";this.b.cw=b.m(a,g.Tb)||b.m(a,g.yc)||"";this.b.ci=b.m(a,g.Rb)||b.m(a,g.vc)||
"";this.b.cf=b.m(a,g.Wb)||b.m(a,g.xc)||"";this.b.cu=b.m(a,g.Sb)||b.m(a,g.uc)||""},init:function(){try{this.rc(),0===this.b.nv?this.pc():this.La(),h.c=this,this.pb(),this.ob(),y.I("pv-b"),this.nc()}catch(a){var b=[];b.push("si="+c.id);b.push("n="+encodeURIComponent(a.name));b.push("m="+encodeURIComponent(a.message));b.push("r="+encodeURIComponent(document.referrer));e.log(g.ea+"//"+g.Ca+"?"+b.join("&"))}},nc:function(){function a(){y.I("pv-d")}this.Ra?(this.wa=t,this.b.et=0,this.b.ep="",this.b.p=u(n.A("pageview")),
this.b.vl=k.T()+k.J(),this.i(a),this.b.p=""):a();this.F=+new Date;n.r("pageview")},i:function(a){if(this.Sa){var b=this;b.b.rnd=Math.round(Math.random()*g.X);y.I("stag-b");var d=g.ea+"//"+g.Ca+"?"+b.Za();y.I("stag-d");b.jb(d);e.log(d,function(d){b.Ya(d);f.e(a,"Function")&&a.call(b)})}},pb:function(){var a=document.location.hash.substring(1),d=RegExp(c.id),e=b.S(document.referrer)===g.cb?1:0,f=b.m(a,"jn"),k=/^heatlink$|^select$|^pageclick$/.test(f);a&&(d.test(a)&&e&&k)&&(this.b.rnd=Math.round(Math.random()*
g.X),a=document.createElement("script"),a.setAttribute("type","text/javascript"),a.setAttribute("charset","utf-8"),a.setAttribute("src",g.protocol+"//"+c.js+f+".js?"+this.b.rnd),f=document.getElementsByTagName("script")[0],f.parentNode.insertBefore(a,f))},ob:function(){if(window.postMessage&&window.self!==window.parent){var a=this;w.d(window,"message",function(d){if(b.S(d.origin)===g.cb){d=d.data||{};var e=d.jn||"",f=/^customevent$/.test(e);if(RegExp(c.id).test(d.sd||"")&&f)a.b.rnd=Math.round(Math.random()*
g.X),p(g.protocol+"//"+c.js+e+".js?"+a.b.rnd)}});window.parent.postMessage({id:c.id,url:document.location.href,status:"__Messenger__hmLoaded"},"*")}},jb:function(a){var b;try{b=q.parse(l.get("Hm_unsent_"+c.id)||"[]")}catch(d){b=[]}var e=this.b.u?"":"&u="+encodeURIComponent(document.location.href);b.push(a.replace(/^https?:\/\//,"")+e);l.set("Hm_unsent_"+c.id,q.stringify(b))},Ya:function(a){var b;try{b=q.parse(l.get("Hm_unsent_"+c.id)||"[]")}catch(d){b=[]}if(b.length){a=a.replace(/^https?:\/\//,"");
for(var e=0;e<b.length;e++)if(a.replace(/&u=[^&]*/,"")===b[e].replace(/&u=[^&]*/,"")){b.splice(e,1);break}b.length?l.set("Hm_unsent_"+c.id,q.stringify(b)):this.La()}},La:function(){l.remove("Hm_unsent_"+c.id)},pc:function(){var a=this,b;try{b=q.parse(l.get("Hm_unsent_"+c.id)||"[]")}catch(d){b=[]}if(b.length)for(var f=function(b){e.log(g.ea+"//"+b,function(b){a.Ya(b)})},k=0;k<b.length;k++)f(b[k])},Oa:function(){return Math.round(+new Date/1E3)%65535}};return new a})();
(function(){var a=mt.event,b=mt.lang,e=h.z;if(c.kbtrk&&"undefined"!==typeof h.c){h.c.b.kb=b.ya(h.c.b.kb)?h.c.b.kb:0;var d=function(){h.c.b.et=85;h.c.b.ep=h.c.b.kb;h.c.i()};a.d(document,"keyup",function(){h.c.b.kb++});a.d(window,"unload",function(){d()});setInterval(d,e.bc)}})();var C=h.z,D=h.load;c.pt&&D([C.protocol,"//ada.baidu.com/phone-tracker/insert_bdtj?sid=",c.pt].join(""));
(function(){var a=mt.h,b=mt.lang,e=mt.event,d=mt.o;if("undefined"!==typeof h.c&&(c.med||(!a.xa||7<a.Hb())&&c.cvcc)){var f,m,k,l,q=function(a){if(a.item){for(var b=a.length,d=Array(b);b--;)d[b]=a[b];return d}return[].slice.call(a)},w=function(a,b){for(var d in a)if(a.hasOwnProperty(d)&&b.call(a,d,a[d])===x)return x},s=function(a,e){var g={};g.n=f;g.t="clk";g.v=a;if(e){var l=e.getAttribute("href"),m=e.getAttribute("onclick")?""+e.getAttribute("onclick"):v,n=e.getAttribute("id")||"";k.test(l)?(g.sn=
"mediate",g.snv=l):b.e(m,"String")&&k.test(m)&&(g.sn="wrap",g.snv=m);g.id=n}h.c.b.et=86;h.c.b.ep=d.stringify(g);h.c.i();for(g=+new Date;400>=+new Date-g;);};if(c.med)m="/zoosnet",f="swt",k=/swt|zixun|call|chat|zoos|business|talk|kefu|openkf|online|\/LR\/Chatpre\.aspx/i,l={click:function(){for(var a=[],b=q(document.getElementsByTagName("a")),b=[].concat.apply(b,q(document.getElementsByTagName("area"))),b=[].concat.apply(b,q(document.getElementsByTagName("img"))),d,e,f=0,g=b.length;f<g;f++)d=b[f],e=
d.getAttribute("onclick"),d=d.getAttribute("href"),(k.test(e)||k.test(d))&&a.push(b[f]);return a}};else if(c.cvcc){m="/other-comm";f="other";k=c.cvcc.q||r;var n=c.cvcc.id||r;l={click:function(){for(var a=[],b=q(document.getElementsByTagName("a")),b=[].concat.apply(b,q(document.getElementsByTagName("area"))),b=[].concat.apply(b,q(document.getElementsByTagName("img"))),d,e,f,g=0,l=b.length;g<l;g++)d=b[g],k!==r?(e=d.getAttribute("onclick"),f=d.getAttribute("href"),n?(d=d.getAttribute("id"),(k.test(e)||
k.test(f)||n.test(d))&&a.push(b[g])):(k.test(e)||k.test(f))&&a.push(b[g])):n!==r&&(d=d.getAttribute("id"),n.test(d)&&a.push(b[g]));return a}}}if("undefined"!==typeof l&&"undefined"!==typeof k){var u;m+=/\/$/.test(m)?"":"/";var g=function(a,d){if(u===d)return s(m+a,d),x;if(b.e(d,"Array")||b.e(d,"NodeList"))for(var e=0,f=d.length;e<f;e++)if(u===d[e])return s(m+a+"/"+(e+1),d[e]),x};e.d(document,"mousedown",function(a){a=a||window.event;u=a.target||a.srcElement;var d={};for(w(l,function(a,e){d[a]=b.e(e,
"Function")?e():document.getElementById(e)});u&&u!==document&&w(d,g)!==x;)u=u.parentNode})}}})();(function(){var a=mt.f,b=mt.lang,e=mt.event,d=mt.o;if("undefined"!==typeof h.c&&b.e(c.cvcf,"Array")&&0<c.cvcf.length){var f={gb:function(){for(var b=c.cvcf.length,d,l=0;l<b;l++)(d=a.Ma(decodeURIComponent(c.cvcf[l])))&&e.d(d,"click",f.qa())},qa:function(){return function(){h.c.b.et=86;var a={n:"form",t:"clk"};a.id=this.id;h.c.b.ep=d.stringify(a);h.c.i()}}};a.Xa(function(){f.gb()})}})();
(function(){var a=mt.event,b=mt.o;if(c.med&&"undefined"!==typeof h.c){var e={n:"anti",sb:0,kb:0,clk:0},d=function(){h.c.b.et=86;h.c.b.ep=b.stringify(e);h.c.i()};a.d(document,"click",function(){e.clk++});a.d(document,"keyup",function(){e.kb=1});a.d(window,"scroll",function(){e.sb++});a.d(window,"load",function(){setTimeout(d,5E3)})}})();})();
